using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Magi.LedgeBoardGame.Models;

namespace Magi.LedgeBoardGame.Tests.EditMode
{
    [TestFixture]
    public class TokenStackTests
    {
        [Test]
        public void EmptyStack_ShouldHaveNoBottomTone()
        {
            var stack = new TokenStack();
            Assert.IsTrue(stack.IsEmpty);
            Assert.IsFalse(stack.BottomTone.HasValue);
        }

        [Test]
        public void PlaceOnEmpty_ShouldLock()
        {
            var stack = new TokenStack();
            var result = stack.ResolveEntry(Tone.Light, 1);

            Assert.AreEqual(MoveResult.Lock, result);
            Assert.AreEqual(1, stack.LightCount);
            Assert.AreEqual(Tone.Light, stack.BottomTone);
            Assert.IsTrue(stack.IsLocked(Tone.Light));
            Assert.IsFalse(stack.CanMove(Tone.Light));
        }

        [Test]
        public void StackSameTone_ShouldStack()
        {
            var stack = new TokenStack(1, 0, Tone.Light);
            var result = stack.ResolveEntry(Tone.Light, 1);

            Assert.AreEqual(MoveResult.Stack, result);
            Assert.AreEqual(2, stack.LightCount);
            Assert.AreEqual(Tone.Light, stack.BottomTone);
            Assert.IsTrue(stack.IsStack(Tone.Light));
            Assert.IsTrue(stack.CanMove(Tone.Light));
        }

        [Test]
        public void ClearOppositeTone_ShouldClear()
        {
            var stack = new TokenStack(2, 0, Tone.Light);
            var result = stack.ResolveEntry(Tone.Dark, 1);

            Assert.AreEqual(MoveResult.Clear, result);
            Assert.AreEqual(1, stack.LightCount);
            Assert.AreEqual(0, stack.DarkCount);
            Assert.AreEqual(Tone.Light, stack.BottomTone);
            Assert.IsTrue(stack.IsLocked(Tone.Light));
        }

        [Test]
        public void ClearToEmpty_ShouldResetBottomTone()
        {
            var stack = new TokenStack(1, 0, Tone.Light);
            var result = stack.ResolveEntry(Tone.Dark, 1);

            Assert.AreEqual(MoveResult.Clear, result);
            Assert.IsTrue(stack.IsEmpty);
            Assert.IsFalse(stack.BottomTone.HasValue);
        }

        [Test]
        public void BottomToken_CannotMove()
        {
            var stack = new TokenStack(1, 0, Tone.Light);
            Assert.IsFalse(stack.CanMove(Tone.Light));

            stack = new TokenStack(0, 1, Tone.Dark);
            Assert.IsFalse(stack.CanMove(Tone.Dark));
        }

        [Test]
        public void StackedTokens_CanMove()
        {
            var stack = new TokenStack(2, 0, Tone.Light);
            Assert.IsTrue(stack.CanMove(Tone.Light));

            stack = new TokenStack(3, 0, Tone.Light);
            Assert.IsTrue(stack.CanMove(Tone.Light));
        }

        [Test]
        public void MixedStack_AfterClear_MaintainsBottomLock()
        {
            var stack = new TokenStack(3, 0, Tone.Light);
            stack.ResolveEntry(Tone.Dark, 2);

            Assert.AreEqual(1, stack.LightCount);
            Assert.AreEqual(0, stack.DarkCount);
            Assert.AreEqual(Tone.Light, stack.BottomTone);
            Assert.IsTrue(stack.IsLocked(Tone.Light));
            Assert.IsFalse(stack.CanMove(Tone.Light));
        }

        [Test]
        public void RemoveOne_UpdatesCorrectly()
        {
            var stack = new TokenStack(3, 0, Tone.Light);
            stack.RemoveOne(Tone.Light);

            Assert.AreEqual(2, stack.LightCount);
            Assert.AreEqual(Tone.Light, stack.BottomTone);
            Assert.IsTrue(stack.CanMove(Tone.Light));
        }

        [Test]
        public void RemoveLastToken_ClearsBottomTone()
        {
            var stack = new TokenStack(1, 0, Tone.Light);
            stack.RemoveOne(Tone.Light);

            Assert.IsTrue(stack.IsEmpty);
            Assert.IsFalse(stack.BottomTone.HasValue);
        }
    }

    /// The twelve-colour Ledge Wheel and the relationships between colours.
    ///
    /// Lives in this file rather than its own, deliberately: a new .cs under
    /// Assets would need a Unity-generated .meta, and hand-authoring GUIDs
    /// causes churn across machines. This file already has one.
    ///
    /// IMPORTANT TEST DESIGN NOTE: the expected 12x12 table below is built from
    /// an EXPLICIT list of the twelve adjacent pairs and the six opposite pairs,
    /// not from index arithmetic. If the expectations were generated by the same
    /// modular arithmetic the production code uses, the table would only prove
    /// the code is self-consistent - not that it matches the wheel. The literal
    /// pair lists are the actual anchor to the design.
    [TestFixture]
    public class LedgeColorTests
    {
        /// The twelve colours in canonical ring order.
        private static readonly LedgeColor[] Ring =
        {
            LedgeColor.Ela, LedgeColor.Biz, LedgeColor.Yun, LedgeColor.Jutu,
            LedgeColor.Glei, LedgeColor.Sace, LedgeColor.Rha, LedgeColor.Dau,
            LedgeColor.Wim, LedgeColor.Pfi, LedgeColor.Quae, LedgeColor.Vei,
        };

        /// The twelve adjacent pairs, written out rather than derived.
        private static readonly LedgeColor[][] AdjacentPairs =
        {
            new[] { LedgeColor.Ela, LedgeColor.Biz },
            new[] { LedgeColor.Biz, LedgeColor.Yun },
            new[] { LedgeColor.Yun, LedgeColor.Jutu },
            new[] { LedgeColor.Jutu, LedgeColor.Glei },
            new[] { LedgeColor.Glei, LedgeColor.Sace },
            new[] { LedgeColor.Sace, LedgeColor.Rha },
            new[] { LedgeColor.Rha, LedgeColor.Dau },
            new[] { LedgeColor.Dau, LedgeColor.Wim },
            new[] { LedgeColor.Wim, LedgeColor.Pfi },
            new[] { LedgeColor.Pfi, LedgeColor.Quae },
            new[] { LedgeColor.Quae, LedgeColor.Vei },
            new[] { LedgeColor.Vei, LedgeColor.Ela },
        };

        /// The six opposite pairs. These are the wheel's axes and are the
        /// load-bearing claim of this whole fixture:
        ///   Social Ela/Rha - Nature Biz/Dau - Physical Yun/Wim
        ///   Tech Jutu/Pfi  - Mental Glei/Quae - Magic Sace/Vei
        private static readonly LedgeColor[][] OppositePairs =
        {
            new[] { LedgeColor.Ela, LedgeColor.Rha },
            new[] { LedgeColor.Biz, LedgeColor.Dau },
            new[] { LedgeColor.Yun, LedgeColor.Wim },
            new[] { LedgeColor.Jutu, LedgeColor.Pfi },
            new[] { LedgeColor.Glei, LedgeColor.Quae },
            new[] { LedgeColor.Sace, LedgeColor.Vei },
        };

        [Test]
        public void Wheel_has_exactly_twelve_colours()
        {
            Assert.AreEqual(12, Enum.GetValues(typeof(LedgeColor)).Length);
        }

        [Test]
        public void Ring_order_matches_the_canonical_wedge_indices()
        {
            for (int i = 0; i < Ring.Length; i++)
                Assert.AreEqual(i, (int)Ring[i], Ring[i] + " must sit at wedge " + i);
        }

        [Test]
        public void The_six_axis_pairs_are_opposite_in_both_directions()
        {
            foreach (var pair in OppositePairs)
            {
                Assert.AreEqual(
                    LedgeColorRelationship.Opposite, LedgeColorWheel.Relate(pair[0], pair[1]),
                    pair[0] + " / " + pair[1] + " must be Opposite");
                Assert.AreEqual(
                    LedgeColorRelationship.Opposite, LedgeColorWheel.Relate(pair[1], pair[0]),
                    pair[1] + " / " + pair[0] + " must be Opposite");
            }
        }

        [Test]
        public void Opposite_lookup_returns_the_axis_partner()
        {
            foreach (var pair in OppositePairs)
            {
                Assert.AreEqual(pair[1], LedgeColorWheel.Opposite(pair[0]));
                Assert.AreEqual(pair[0], LedgeColorWheel.Opposite(pair[1]));
            }
        }

        [Test]
        public void Every_colour_has_exactly_one_opposite_and_is_never_its_own()
        {
            foreach (var c in Ring)
            {
                var opp = LedgeColorWheel.Opposite(c);
                Assert.AreNotEqual(c, opp);
                Assert.AreEqual(c, LedgeColorWheel.Opposite(opp), "Opposition is involutive");
            }
        }

        [Test]
        public void Full_twelve_by_twelve_relationship_table_is_correct()
        {
            var expected = BuildExpectedTable();

            foreach (var a in Ring)
                foreach (var b in Ring)
                    Assert.AreEqual(
                        expected[Key(a, b)], LedgeColorWheel.Relate(a, b),
                        "Relate(" + a + ", " + b + ")");
        }

        [Test]
        public void Expected_table_partitions_all_144_ordered_pairs()
        {
            var expected = BuildExpectedTable();
            Assert.AreEqual(144, expected.Count);
            Assert.AreEqual(12, expected.Values.Count(r => r == LedgeColorRelationship.Same));
            Assert.AreEqual(24, expected.Values.Count(r => r == LedgeColorRelationship.Adjacent));
            Assert.AreEqual(12, expected.Values.Count(r => r == LedgeColorRelationship.Opposite));
            Assert.AreEqual(96, expected.Values.Count(r => r == LedgeColorRelationship.Unrelated));
        }

        [Test]
        public void Relationships_are_symmetric()
        {
            foreach (var a in Ring)
                foreach (var b in Ring)
                    Assert.AreEqual(
                        LedgeColorWheel.Relate(a, b), LedgeColorWheel.Relate(b, a),
                        "Relate is symmetric for " + a + "/" + b);
        }

        [Test]
        public void A_colour_is_Same_as_itself()
        {
            foreach (var c in Ring)
                Assert.AreEqual(LedgeColorRelationship.Same, LedgeColorWheel.Relate(c, c));
        }

        [Test]
        public void Adjacent_pairs_wrap_around_the_ring()
        {
            Assert.AreEqual(
                LedgeColorRelationship.Adjacent,
                LedgeColorWheel.Relate(LedgeColor.Vei, LedgeColor.Ela));
        }

        [Test]
        public void Multicolour_uses_the_strongest_relationship_present()
        {
            var rhaDau = new[] { LedgeColor.Rha, LedgeColor.Dau };
            var elaBiz = new[] { LedgeColor.Ela, LedgeColor.Biz };

            Assert.AreEqual(
                LedgeColorRelationship.Opposite, LedgeColorWheel.Strongest(rhaDau, elaBiz));
        }

        [Test]
        public void Multicolour_finds_Same_when_a_colour_is_shared()
        {
            var rhaDau = new[] { LedgeColor.Rha, LedgeColor.Dau };
            var rhaSace = new[] { LedgeColor.Rha, LedgeColor.Sace };

            Assert.AreEqual(
                LedgeColorRelationship.Same, LedgeColorWheel.Strongest(rhaDau, rhaSace));
        }

        [Test]
        public void Multicolour_mirror_of_a_two_colour_card_is_Same()
        {
            var rhaDau = new[] { LedgeColor.Rha, LedgeColor.Dau };

            Assert.AreEqual(
                LedgeColorRelationship.Same, LedgeColorWheel.Strongest(rhaDau, rhaDau));
        }

        [Test]
        public void Multicolour_reports_Unrelated_when_nothing_connects()
        {
            var elaBiz = new[] { LedgeColor.Ela, LedgeColor.Biz };
            var gleiQuae = new[] { LedgeColor.Glei, LedgeColor.Quae };

            Assert.AreEqual(
                LedgeColorRelationship.Unrelated, LedgeColorWheel.Strongest(elaBiz, gleiQuae));
        }

        [Test]
        public void HasRelationship_finds_a_specific_relationship_regardless_of_strength()
        {
            var rhaEla = new[] { LedgeColor.Rha, LedgeColor.Ela };
            var rhaBiz = new[] { LedgeColor.Rha, LedgeColor.Biz };

            Assert.AreEqual(
                LedgeColorRelationship.Same, LedgeColorWheel.Strongest(rhaEla, rhaBiz),
                "Same outranks Opposite under the documented precedence");
            Assert.IsTrue(
                LedgeColorWheel.HasRelationship(rhaEla, rhaBiz, LedgeColorRelationship.Opposite),
                "...but the Opposite relation is still discoverable");
        }

        [Test]
        public void Empty_colour_sets_are_Unrelated_rather_than_throwing()
        {
            var none = new LedgeColor[0];
            var rha = new[] { LedgeColor.Rha };

            Assert.AreEqual(LedgeColorRelationship.Unrelated, LedgeColorWheel.Strongest(none, rha));
            Assert.AreEqual(LedgeColorRelationship.Unrelated, LedgeColorWheel.Strongest(none, none));
        }

        [Test]
        public void Strongest_rejects_null_input()
        {
            var rha = new[] { LedgeColor.Rha };
            Assert.Throws<ArgumentNullException>(() => LedgeColorWheel.Strongest(null, rha));
            Assert.Throws<ArgumentNullException>(() => LedgeColorWheel.Strongest(rha, null));
        }

        private static string Key(LedgeColor a, LedgeColor b)
        {
            return (int)a + ":" + (int)b;
        }

        private static Dictionary<string, LedgeColorRelationship> BuildExpectedTable()
        {
            var table = new Dictionary<string, LedgeColorRelationship>();

            foreach (var a in Ring)
                foreach (var b in Ring)
                    table[Key(a, b)] = LedgeColorRelationship.Unrelated;

            foreach (var c in Ring)
                table[Key(c, c)] = LedgeColorRelationship.Same;

            foreach (var pair in AdjacentPairs)
            {
                table[Key(pair[0], pair[1])] = LedgeColorRelationship.Adjacent;
                table[Key(pair[1], pair[0])] = LedgeColorRelationship.Adjacent;
            }

            foreach (var pair in OppositePairs)
            {
                table[Key(pair[0], pair[1])] = LedgeColorRelationship.Opposite;
                table[Key(pair[1], pair[0])] = LedgeColorRelationship.Opposite;
            }

            return table;
        }
    }
}
